### ISSUE TITLE
Text 2 Kata tidak muncul hasil

### ISSUE THREAD

**Issue by winbotscript** [djsamm88/api-line#1]
Hai gan, maaf mau tanya ketika kita input 2 kata seperti Thank You, Terima Kasih atau Met Pagi kenapa ga ada balasan nya yah ??? Tolong bantuannya

**Comment by YogaSakti** [comment]
if($pesan_datang == 'Thank You') 
dibikin gitu aja

**Comment by risyad224** [comment]
ajarin dong _-

cara buat command seperti get dp @

**Comment by YogaSakti** [comment]
baca dokumentasi apinya line aja gan :)

**Comment by djsamm88** [comment]
close ya
